version: 2

project_name: vmm

before:
  hooks:
    - go mod tidy

builds:
  - id: vmm
    main: ./cmd/vmm
    binary: vmm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: vmm
    builds:
      - vmm
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - scripts/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: raesene
    name: baremetalvmm
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
